// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rtbiwbupzrbfrijwyjua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0Yml3YnVwenJiZnJpand5anVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDU4MTYsImV4cCI6MjA3MDEyMTgxNn0.r7ZdvRNOURhToDFxQs446BoZBoAWfAWuAxcn4but-4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);